from __future__ import annotations

from copy import deepcopy
from typing import Any

from .data_contract import default_data_contract


SCHEMA_VERSION = "commerce-data-schema-v1"


COMMERCE_DATA_SCHEMAS: dict[str, dict[str, Any]] = {
    "Product": {
        "purpose": "Normalize products collected from TikTok Shop, Amazon, Walmart, Etsy, SHEIN, POD, and future channels.",
        "record_types": ["hot_link", "platform_ranking_signal", "money_case", "selection_playbook"],
        "id_fields": ["platform", "country", "product_id", "product_url", "product_name"],
        "required_fields": ["product_name", "platform", "country", "category_path", "source_url"],
        "recommended_fields": [
            "product_id",
            "brand",
            "seller_name",
            "price",
            "currency",
            "rank_position",
            "sales_count",
            "gmv",
            "review_count",
            "rating",
            "lifecycle_stage",
            "risk_status",
            "source_confidence",
        ],
        "quality_fields": ["source_type", "source_confidence", "snapshot_window", "collected_at"],
        "downstream_agents": ["AI Ecommerce Director", "Product Intelligence", "Listing Intelligence", "Risk Intelligence"],
    },
    "Creator": {
        "purpose": "Normalize creators, influencers, official accounts, and channel accounts for outreach and content performance.",
        "record_types": ["influencer_cooperation", "creator_spike_event", "social_account_profile"],
        "id_fields": ["platform", "country", "creator_handle", "profile_url"],
        "required_fields": ["creator_handle", "platform", "country"],
        "recommended_fields": [
            "profile_url",
            "follower_count",
            "avg_views",
            "engagement_rate",
            "quote_price",
            "contact_email",
            "contact_phone",
            "whatsapp",
            "dm_url",
            "cooperation_status",
            "roi",
            "creator_grade",
        ],
        "quality_fields": ["last_observed_at", "source_confidence", "contact_verified"],
        "downstream_agents": ["Influencer Intelligence", "Viral Content Intelligence", "Content Director"],
    },
    "Video": {
        "purpose": "Normalize TikTok-first product videos, creator videos, owned account videos, and viral case studies.",
        "record_types": ["viral_content_signal", "video_breakdown", "video_script", "tk_case_learning"],
        "id_fields": ["video_url", "platform", "creator_handle"],
        "required_fields": ["video_url", "platform", "product_name"],
        "recommended_fields": [
            "creator_handle",
            "views",
            "likes",
            "comments",
            "shares",
            "hook_text",
            "hook_type",
            "timeline_structure",
            "scene",
            "emotion",
            "caption_text",
            "spoken_text",
            "music_risk",
            "replicate_plan",
        ],
        "quality_fields": ["collected_at", "source_confidence", "analysis_version"],
        "downstream_agents": ["Viral Content Intelligence", "Content Director", "Advertising Director"],
    },
    "Keyword": {
        "purpose": "Normalize product, identity, interest, occupation, emotion, holiday, and geo keywords.",
        "record_types": ["culture_label", "holiday_opportunity", "selection_playbook", "knowledge_item"],
        "id_fields": ["keyword", "language", "market"],
        "required_fields": ["keyword", "keyword_type", "language"],
        "recommended_fields": [
            "market",
            "platform",
            "growth_signal",
            "competition_level",
            "search_intent",
            "related_products",
            "related_creators",
            "related_holidays",
        ],
        "quality_fields": ["source_type", "source_confidence", "last_seen_at"],
        "downstream_agents": ["Keyword Intelligence", "Listing Intelligence", "Viral Content Intelligence"],
    },
    "Listing": {
        "purpose": "Normalize platform listing copy, images, price, compliance status, and optimization results.",
        "record_types": ["store_operation_event", "video_script", "compliance_term", "review_insight"],
        "id_fields": ["platform", "store_id", "seller_sku", "listing_url"],
        "required_fields": ["product_name", "platform", "store_id"],
        "recommended_fields": [
            "title",
            "bullet_points",
            "description",
            "main_image_url",
            "detail_image_urls",
            "price",
            "discount",
            "tags",
            "conversion_rate",
            "review_score",
            "risk_status",
        ],
        "quality_fields": ["last_updated_at", "approved_by", "source_confidence"],
        "downstream_agents": ["Listing Intelligence", "Risk Intelligence", "Advertising Director"],
    },
    "Store": {
        "purpose": "Normalize store identity, operating country, platform, browser profile, and daily operating status.",
        "record_types": ["store_profile", "store_metric_snapshot", "store_health_event"],
        "id_fields": ["platform", "country_code", "store_id"],
        "required_fields": ["store_id", "store_name", "platform", "country_code"],
        "recommended_fields": [
            "store_group",
            "browser_profile",
            "bit_profile_id",
            "currency",
            "timezone",
            "language",
            "fulfillment_model",
            "operating_status",
            "health_status",
        ],
        "quality_fields": ["credential_ref", "legal_entity_ref", "last_checked_at"],
        "downstream_agents": ["AI Ecommerce Director", "OMS Director", "Risk Intelligence", "Finance Officer"],
    },
    "Order": {
        "purpose": "Normalize order, return, refund, settlement, fulfillment, and profit snapshots.",
        "record_types": ["store_metric_snapshot", "execution_result", "review_insight"],
        "id_fields": ["platform", "store_id", "order_id"],
        "required_fields": ["platform", "store_id", "order_id", "order_date"],
        "recommended_fields": [
            "product_id",
            "seller_sku",
            "unit_count",
            "total_revenue",
            "refund_amount",
            "settlement_amount",
            "shipping_fee",
            "platform_fee",
            "profit",
            "fulfillment_status",
            "return_reason",
        ],
        "quality_fields": ["report_type", "snapshot_start", "snapshot_end", "source_confidence"],
        "downstream_agents": ["OMS Director", "Finance Officer", "Data Review Analyst"],
    },
    "Supplier": {
        "purpose": "Normalize factory, supplier, POD blank, inventory, cost, SLA, and dispatch constraints.",
        "record_types": ["supply_chain", "pod_admin_snapshot"],
        "id_fields": ["supplier_id", "factory_id", "blank_id"],
        "required_fields": ["supplier_name", "country", "product_type"],
        "recommended_fields": [
            "factory_id",
            "blank_id",
            "color",
            "size_range",
            "weight_gsm",
            "inventory_qty",
            "unit_cost",
            "production_days",
            "shipping_days",
            "sla_score",
            "quality_score",
        ],
        "quality_fields": ["last_inventory_sync_at", "source_confidence", "contract_status"],
        "downstream_agents": ["Supply Chain Director", "Factory Dispatcher", "OMS Director"],
    },
    "Signal": {
        "purpose": "Autonomous v2 signal layer for trend, anomaly, seasonality, and saturation detection.",
        "record_types": ["signal_event", "signal_snapshot", "signal_threshold", "signal_alert", "signal_weight"],
        "id_fields": ["signal_id", "entity_type", "entity_id", "metric_name", "timestamp"],
        "required_fields": ["signal_id", "engine_type", "entity_type", "entity_id", "metric_name", "platform", "timestamp"],
        "recommended_fields": [
            "baseline_value",
            "current_value",
            "delta",
            "velocity",
            "z_score",
            "seasonal_score",
            "saturation_score",
            "confidence",
            "risk_score",
        ],
        "quality_fields": ["source_record_id", "status", "confidence", "calculated_at_utc"],
        "downstream_agents": ["AI Ecommerce Director", "Signal Engine", "Opportunity Detection Engine"],
    },
    "Hypothesis": {
        "purpose": "Convert signals into commercial assumptions that can be risk checked and tested.",
        "record_types": ["hypothesis", "hypothesis_evidence", "hypothesis_score"],
        "id_fields": ["hypothesis_id", "signal_id"],
        "required_fields": ["hypothesis_id", "signal_id", "opportunity_type", "hypothesis_text", "status"],
        "recommended_fields": ["related_entities", "expected_profit", "risk_score", "confidence_score", "priority_score"],
        "quality_fields": ["score_version", "evidence_count", "created_at_utc"],
        "downstream_agents": ["AI Ecommerce Director", "Experiment Planner", "Risk Intelligence"],
    },
    "Experiment": {
        "purpose": "Controlled small-budget test layer for product, content, creator, offer, listing, and ads experiments.",
        "record_types": ["experiment", "experiment_variant", "experiment_metric", "experiment_stop_rule", "experiment_scale_rule", "experiment_outcome"],
        "id_fields": ["experiment_id", "hypothesis_id"],
        "required_fields": ["experiment_id", "hypothesis_id", "platform", "budget_limit", "state"],
        "recommended_fields": ["cpa_limit", "roi_target", "time_window", "stop_loss_rule", "scale_rule", "owner"],
        "quality_fields": ["state", "started_at_utc", "ended_at_utc", "manual_execution_required"],
        "downstream_agents": ["AI Ecommerce Director", "Advertising Director", "Viral Content Intelligence", "Data Review Analyst"],
    },
    "Reinforcement": {
        "purpose": "Outcome-to-memory layer that raises successful patterns and lowers failed patterns.",
        "record_types": ["pattern_weight", "pattern_history", "strategy_adjustment", "priority_rebalance_log"],
        "id_fields": ["pattern_weight_id", "pattern_type", "pattern_value"],
        "required_fields": ["pattern_type", "pattern_value", "weight", "last_updated"],
        "recommended_fields": ["success_count", "failure_count", "delta", "reason", "source_experiment_id"],
        "quality_fields": ["evidence_count", "last_updated", "source_confidence"],
        "downstream_agents": ["AI Ecommerce Director", "Knowledge Reviewer", "Data Review Analyst"],
    },
    "Priority": {
        "purpose": "Backlog and task priority layer using expected_profit * confidence * time_sensitivity * (1 - risk).",
        "record_types": ["task_priority", "backlog", "priority_score"],
        "id_fields": ["priority_score_id", "entity_type", "entity_id", "calculated_at_utc"],
        "required_fields": ["entity_type", "entity_id", "priority_score", "calculated_at_utc"],
        "recommended_fields": ["expected_profit", "confidence_score", "time_sensitivity", "risk_score", "next_step"],
        "quality_fields": ["score_formula", "score_version", "created_at_utc"],
        "downstream_agents": ["AI Ecommerce Director", "Chief of Staff", "Task Queue"],
    },
    "MarketCoverage": {
        "purpose": "P0 market eyes for category depth, subcategory movement, mid-rank products, long-tail opportunities, keywords, creators, videos, price changes, and review pain points.",
        "record_types": [
            "market_category_snapshot",
            "market_segment_snapshot",
            "category_growth_snapshot",
            "mid_rank_product_signal",
            "long_tail_opportunity",
            "keyword_trend_snapshot",
            "creator_trend_snapshot",
            "video_trend_snapshot",
            "price_trend_snapshot",
            "review_painpoint_snapshot",
            "market_signal",
            "market_hypothesis",
            "market_plan",
            "market_task",
        ],
        "id_fields": ["platform", "country", "category", "segment", "snapshot_id", "signal_id"],
        "required_fields": ["platform", "country", "category", "segment", "run_date"],
        "recommended_fields": [
            "current_value",
            "baseline_7d",
            "baseline_30d",
            "delta_7d",
            "delta_30d",
            "velocity",
            "acceleration",
            "opportunity_score",
            "confidence_score",
            "risk_score",
            "evidence_count",
        ],
        "quality_fields": ["source_record_ids", "is_training_seed", "confidence_score", "evidence_count"],
        "downstream_agents": ["Market Coverage Intelligence Agent", "AI Ecommerce Director", "Signal Engine", "Experiment Planner"],
    },
    "Phase3Expansion": {
        "purpose": "Reserved long-term growth layer for offline retail, offline advertising, HR/interview automation, audience preference, brand matrix, BD, IP co-branding, PR, and brand-led product selection.",
        "record_types": [
            "audience_preference",
            "brand_matrix",
            "brand_style_profile",
            "brand_product_fit_score",
            "offline_store",
            "offline_location_signal",
            "offline_ad_campaign",
            "hr_candidate",
            "interview_record",
            "role_competency_matrix",
            "ip_asset",
            "ip_license",
            "co_brand_project",
            "pr_contact",
            "pr_campaign",
            "business_partner",
            "negotiation_record",
        ],
        "id_fields": ["entity_id", "agent_id", "brand_id", "country", "channel"],
        "required_fields": ["entity_type", "name", "status"],
        "recommended_fields": ["owner_agent", "country", "platform", "risk_score", "confidence_score", "next_review_date"],
        "quality_fields": ["source_confidence", "approval_status", "created_at_utc"],
        "downstream_agents": ["AI Ecommerce Director", "Brand Matrix Agent", "Offline Retail Agent", "Business Development Agent"],
    },
}


COMMERCE_KNOWLEDGE_GRAPH_SCHEMA: dict[str, Any] = {
    "version": "commerce-knowledge-graph-v1",
    "node_types": [
        "product",
        "creator",
        "video",
        "keyword",
        "listing",
        "store",
        "order",
        "supplier",
        "platform",
        "country",
        "category",
        "niche",
        "holiday",
        "risk",
        "strategy",
        "system_layer",
        "market_signal",
        "market_hypothesis",
        "audience",
        "brand",
        "offline_location",
        "ip_asset",
        "business_partner",
    ],
    "edge_types": [
        "relates_to",
        "appears_in",
        "sold_by",
        "created_by",
        "ranks_on",
        "has_keyword",
        "has_risk",
        "belongs_to",
        "co_occurs_with",
        "converts_to",
        "influences",
        "requires_review",
    ],
    "required_edge_fields": ["edge_key", "source_entity", "target_entity", "relation", "weight", "source_type"],
    "weight_policy": {
        "base": "Source trust + evidence + repeated occurrence",
        "raise_when": ["trusted source repeats", "own store data confirms", "top seller case confirms", "platform data confirms"],
        "lower_when": ["low confidence forum", "no evidence", "conflicts with own store data", "policy risk"],
    },
}


AGENT_REGISTRY: list[dict[str, Any]] = [
    {
        "agent": "AI Ecommerce Director",
        "version": "v1",
        "responsibility": "Coordinate product, content, creator, listing, store, risk, and review agents.",
        "inputs": ["Product", "Creator", "Video", "Keyword", "Listing", "Store", "Order", "Supplier", "Knowledge Graph"],
        "outputs": ["daily_meeting", "pending_approvals", "strategy_memory", "risk_summary"],
        "permissions": ["read_all", "draft_actions", "queue_approvals"],
        "automation_level": "L2-L3",
    },
    {
        "agent": "Product Intelligence",
        "version": "v1",
        "responsibility": "Monitor categories, ranking growth, new releases, product lifecycle, and product-market fit.",
        "inputs": ["Product", "Keyword", "Review", "Video"],
        "outputs": ["product_score", "lifecycle_stage", "launch_budget_suggestion"],
        "permissions": ["read_market_data", "draft_product_targets"],
        "automation_level": "L1-L2",
    },
    {
        "agent": "Market Coverage Intelligence Agent",
        "version": "v1",
        "responsibility": "P0 market radar that watches big categories, subcategories, mid-rank products, long-tail opportunities, keywords, creators, TikTok videos, price changes, reviews, platform rules, and risk shifts.",
        "inputs": ["MarketCoverage", "Product", "Creator", "Video", "Keyword", "Review", "Signal"],
        "outputs": ["market_signal", "market_hypothesis", "market_plan", "market_task", "task_queue", "strategy_memory"],
        "permissions": ["read_market_data", "draft_collection_tasks", "draft_hypotheses", "queue_director_review"],
        "automation_level": "L0-L2",
    },
    {
        "agent": "Influencer Intelligence",
        "version": "v1",
        "responsibility": "Build private creator library, score creators, track contacts, ROI, and cooperation fit.",
        "inputs": ["Creator", "Video", "Order"],
        "outputs": ["creator_grade", "outreach_draft", "sample_priority"],
        "permissions": ["read_creator_data", "draft_outreach"],
        "automation_level": "L1-L3",
    },
    {
        "agent": "Viral Content Intelligence",
        "version": "v1",
        "responsibility": "Analyze TikTok videos, scripts, hooks, camera movement, editing, scene, comments, and replication plan.",
        "inputs": ["Video", "Creator", "Product", "Keyword", "Review"],
        "outputs": ["video_breakdown", "store_script", "creator_brief", "replicate_plan"],
        "permissions": ["read_video_data", "draft_scripts"],
        "automation_level": "L1-L2",
    },
    {
        "agent": "Keyword Intelligence",
        "version": "v1",
        "responsibility": "Maintain product, identity, interest, occupation, emotion, holiday, and geo keyword memory.",
        "inputs": ["Keyword", "Product", "Video", "Review"],
        "outputs": ["keyword_score", "long_tail_keywords", "listing_tags"],
        "permissions": ["read_keyword_data", "draft_keywords"],
        "automation_level": "L1-L2",
    },
    {
        "agent": "Listing Intelligence",
        "version": "v1",
        "responsibility": "Draft titles, bullet points, tags, images, pricing suggestions, and platform-specific listing changes.",
        "inputs": ["Listing", "Product", "Keyword", "Review", "Risk"],
        "outputs": ["listing_draft", "image_direction", "price_suggestion"],
        "permissions": ["draft_listing", "queue_approval"],
        "automation_level": "L2-L3",
    },
    {
        "agent": "OMS Director",
        "version": "v1",
        "responsibility": "Analyze order, return, inventory, fulfillment, replenishment, and profit signals.",
        "inputs": ["Order", "Store", "Supplier"],
        "outputs": ["fulfillment_risk", "replenishment_plan", "profit_snapshot"],
        "permissions": ["read_store_data", "draft_ops_actions"],
        "automation_level": "L1-L3",
    },
    {
        "agent": "Supply Chain Director",
        "version": "v1",
        "responsibility": "Recommend factory dispatch by region, cost, inventory, capacity, SLA, and logistics.",
        "inputs": ["Supplier", "Order", "Product", "Store"],
        "outputs": ["dispatch_recommendation", "stock_risk", "cost_plan"],
        "permissions": ["read_supplier_data", "draft_dispatch_plan"],
        "automation_level": "L1-L3",
    },
    {
        "agent": "Risk Intelligence",
        "version": "v1",
        "responsibility": "Review IP, trademark, copyright, platform policy, account health, refund, and complaint risk.",
        "inputs": ["Product", "Listing", "Video", "Review", "Store"],
        "outputs": ["risk_scan", "visibility_recommendation", "manual_review_queue"],
        "permissions": ["read_compliance_data", "block_autonomous_publish"],
        "automation_level": "L1-L3",
    },
    {
        "agent": "Audience Preference Intelligence",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for country, crowd, style, price, content, gifting, and channel preference learning.",
        "inputs": ["MarketCoverage", "Video", "Review", "Keyword", "Store"],
        "outputs": ["audience_preference", "brand_product_fit_score", "strategy_memory"],
        "permissions": ["read_market_data", "draft_strategy_notes"],
        "automation_level": "L0-L1",
    },
    {
        "agent": "Brand Matrix Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for brand portfolio, brand style profiles, brand-led product selection, and multi-country positioning.",
        "inputs": ["Product", "MarketCoverage", "AudiencePreference", "Listing"],
        "outputs": ["brand_matrix", "brand_style_profile", "brand_product_fit_score"],
        "permissions": ["read_brand_data", "draft_brand_strategy"],
        "automation_level": "L0-L1",
    },
    {
        "agent": "Offline Retail Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for future offline store, pop-up, retail channel, shelf, and local country expansion analysis.",
        "inputs": ["Store", "Order", "MarketCoverage", "AudiencePreference"],
        "outputs": ["offline_store", "offline_location_signal", "retail_expansion_plan"],
        "permissions": ["read_ops_data", "draft_offline_plan"],
        "automation_level": "L0-L1",
    },
    {
        "agent": "Offline Advertising Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for future outdoor ads, mall ads, event ads, and offline campaign measurement.",
        "inputs": ["OfflineStore", "AudiencePreference", "BrandMatrix"],
        "outputs": ["offline_ad_campaign", "budget_draft", "measurement_plan"],
        "permissions": ["read_strategy_data", "draft_campaign"],
        "automation_level": "L0-L1",
    },
    {
        "agent": "HR Interview Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for hiring, role competency, interview question banks, candidate scoring, and training plans.",
        "inputs": ["AgentRegistry", "RoleCompetencyMatrix", "FeedbackTicket"],
        "outputs": ["hr_candidate", "interview_record", "role_competency_matrix"],
        "permissions": ["draft_interview", "draft_hiring_score"],
        "automation_level": "L0-L1",
    },
    {
        "agent": "Business Development Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for partner discovery, negotiation memory, brand cooperation, and country channel BD.",
        "inputs": ["BusinessPartner", "NegotiationRecord", "Store", "MarketCoverage"],
        "outputs": ["business_partner", "negotiation_record", "bd_action_draft"],
        "permissions": ["draft_outreach", "queue_approval"],
        "automation_level": "L0-L2",
    },
    {
        "agent": "IP Co-branding Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for IP asset tracking, licensing opportunities, co-branding projects, and authorization proof review.",
        "inputs": ["IPRegistry", "IPAsset", "IPLicense", "Product", "Listing"],
        "outputs": ["ip_asset", "ip_license", "co_brand_project", "manual_review_queue"],
        "permissions": ["read_ip_data", "draft_license_review"],
        "automation_level": "L0-L2",
    },
    {
        "agent": "PR Brand Awareness Agent",
        "version": "v1-reserved",
        "responsibility": "Reserve layer for media contacts, PR events, press kits, brand awareness, and crisis watch.",
        "inputs": ["BrandMatrix", "PRContact", "PRCampaign", "Review"],
        "outputs": ["pr_contact", "pr_campaign", "brand_awareness_report"],
        "permissions": ["draft_pr_plan", "queue_approval"],
        "automation_level": "L0-L1",
    },
    {
        "agent": "Knowledge Reviewer",
        "version": "v1",
        "responsibility": "Score imported knowledge, detect weak evidence, reduce knowledge pollution, and update concept weights.",
        "inputs": ["conversation_import", "knowledge_item", "knowledge_edge", "knowledge_concept_weight"],
        "outputs": ["knowledge_score", "review_status", "concept_weight_delta"],
        "permissions": ["read_knowledge", "write_knowledge_scores"],
        "automation_level": "L0-L2",
    },
    {
        "agent": "Data Review Analyst",
        "version": "v1",
        "responsibility": "Compare imported platform/store data, detect gaps, duplicates, bias, and report confidence.",
        "inputs": ["Product", "Store", "Order", "Video", "Creator"],
        "outputs": ["data_quality_report", "dedupe_report", "missing_data_tasks"],
        "permissions": ["read_all", "draft_collection_tasks"],
        "automation_level": "L1-L2",
    },
]


def default_commerce_data_schema() -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "entities": deepcopy(COMMERCE_DATA_SCHEMAS),
        "data_contract": default_data_contract(),
        "knowledge_graph": deepcopy(COMMERCE_KNOWLEDGE_GRAPH_SCHEMA),
        "agent_registry": deepcopy(AGENT_REGISTRY),
    }


def schema_for(entity_name: str) -> dict[str, Any]:
    for name, schema in COMMERCE_DATA_SCHEMAS.items():
        if name.lower() == str(entity_name or "").lower():
            return deepcopy(schema)
    raise KeyError(f"Unknown commerce schema entity: {entity_name}")


def validate_schema_payload(entity_name: str, payload: dict[str, Any]) -> dict[str, Any]:
    schema = schema_for(entity_name)
    required = schema.get("required_fields", [])
    missing = [field for field in required if payload.get(field) in (None, "")]
    return {
        "entity": entity_name,
        "schema_version": SCHEMA_VERSION,
        "valid": not missing,
        "missing_required_fields": missing,
        "recommended_missing_fields": [field for field in schema.get("recommended_fields", []) if payload.get(field) in (None, "")],
    }


def agent_registry_summary() -> dict[str, Any]:
    return {
        "agent_count": len(AGENT_REGISTRY),
        "agents": [item["agent"] for item in AGENT_REGISTRY],
        "permission_model": "read -> draft -> queue approval; real external actions stay behind confirmation until explicitly promoted.",
    }
