from __future__ import annotations

import re
from typing import Any


RECORD_TYPES = {
    "money_case",
    "influencer_cooperation",
    "supply_chain",
    "selection_playbook",
    "culture_label",
    "holiday_opportunity",
    "hot_link",
    "platform_ranking_signal",
    "store_profile",
    "tk_rule_update",
    "store_health_event",
    "store_operation_event",
    "viral_content_signal",
    "creator_spike_event",
    "video_breakdown",
    "video_script",
    "social_account_profile",
    "video_publish_plan",
    "creative_inspiration",
    "industry_research_asset",
    "compliance_term",
    "ip_image_risk",
    "review_insight",
    "feedback_ticket",
    "collection_job",
    "pod_admin_snapshot",
    "store_metric_snapshot",
    "execution_result",
    "strategy_memory",
    "web_ai_meeting",
    "conversation_import",
    "knowledge_item",
    "knowledge_edge",
    "knowledge_concept_weight",
    "keyword_intelligence",
    "agent_workspace_snapshot",
    "agent_distillation_pack",
    "source_document",
    "raw_asset",
    "import_batch",
    "attachment_asset",
    "knowledge_edge_record",
    "order_item",
    "platform_rule_snapshot",
    "finance_transaction",
    "inventory_ledger",
    "entity_tag_map",
    "experiment_run",
    "action_outcome",
    "approval_request",
    "audit_log",
    "taxonomy_dictionary",
    "pii_vault",
    "learning_event",
    "knowledge_node",
    "agent_registry",
    "enterprise_account",
    "quote",
    "contract_record",
    "inquiry",
    "agent_evaluation",
    "source_chunk",
    "ingestion_run",
    "lineage_event",
    "evidence_claim",
    "policy_document",
    "policy_rule",
    "policy_diff",
    "entity_alias",
    "knowledge_revision",
    "eval_case",
    "eval_run",
    "judge_result",
    "error_slice",
    "rollback_gate",
    "model_registry",
    "prompt_version",
    "event_inbox",
    "event_dedup",
    "task_queue",
    "dead_letter",
    "agent_action_log",
    "data_subject_request",
    "retention_policy",
    "delete_workflow",
    "consent_record",
    "sensitive_data_flag",
    "company",
    "company_user",
    "shared_catalog",
    "quote_line",
    "price_list",
    "settlement",
    "payout",
    "invoice",
    "return_rma",
    "refund_record",
    "performance_alert",
    "account_health",
    "raw_extraction_run",
    "policy_snapshot",
    "banned_term",
    "ip_registry",
    "competitor_snapshot",
    "listing_snapshot",
    "price_history",
    "video_scene",
    "video_highlight_frame",
    "video_comment",
    "video_comment_intelligence",
    "knowledge_provenance",
    "knowledge_score_record",
    "concept_weight_history",
    "quality_metric_snapshot",
    "claim_requirement",
    "compliance_artifact",
    "content_rights_asset",
    "commercial_disclosure",
    "enforcement_event",
    "appeal_case",
    "query_snapshot",
    "creative_snapshot",
    "seasonal_event",
    "creative_pattern",
    "platform_playbook",
    "product_lexicon",
    "holiday_calendar",
    "restricted_term",
    "ip_entity",
    "creative_asset",
    "creative_decomposition",
    "lead_signal",
    "creative_pattern_weight",
    "agent_permission",
    "agent_run",
    "execution_plan",
    "plan_task",
    "agent_review",
    "signal_baseline",
    "experiment_rule",
    "signal_event",
    "signal_snapshot",
    "signal_threshold",
    "signal_alert",
    "signal_weight",
    "hypothesis",
    "hypothesis_evidence",
    "hypothesis_score",
    "experiment",
    "experiment_variant",
    "experiment_metric",
    "experiment_stop_rule",
    "experiment_scale_rule",
    "experiment_outcome",
    "pattern_weight",
    "pattern_history",
    "strategy_adjustment",
    "priority_rebalance_log",
    "task_priority",
    "backlog",
    "priority_score",
    "knowledge_distillation_item",
    "risk_intelligence_quarantine",
    "word_bank_entry",
    "tenant",
    "workspace",
    "user",
    "role",
    "permission",
    "role_permission",
    "user_role",
    "license",
    "store_binding",
    "export_log",
    "customer_feedback",
    "agent_outcome",
    "training_feedback",
    "beta_workspace",
    "report_watermark",
    "seller_profile",
    "seller_mode_assessment",
    "seller_capability_score",
    "seller_strategy_package",
    "testing_seller_playbook",
    "launch_seller_playbook",
    "factory_seller_playbook",
    "brand_seller_playbook",
    "factory_product_line",
    "factory_capacity_profile",
    "country_market_fit",
    "platform_fit_score",
    "landed_cost_scenario",
    "tariff_classification_record",
    "tax_entity_scenario",
    "company_structure_option",
    "trade_route_scenario",
    "compliance_advisor_review",
    "manufacturing_origin_option",
    "brand_product_development_plan",
    "factory_export_plan",
}

RECORD_TYPE_ALIASES = {
    "influencer": "influencer_cooperation",
    "creator": "influencer_cooperation",
    "viral_link": "hot_link",
    "hot_product": "hot_link",
    "link": "hot_link",
    "marketplace_ranking": "platform_ranking_signal",
    "platform_ranking": "platform_ranking_signal",
    "amazon_ranking": "platform_ranking_signal",
    "amazon_bsr": "platform_ranking_signal",
    "amazon_bs_new": "platform_ranking_signal",
    "amazon_bs_new_signal": "platform_ranking_signal",
    "amazon_bs.new": "platform_ranking_signal",
    "amazon_bs/new": "platform_ranking_signal",
    "tiktok_shop_ranking": "platform_ranking_signal",
    "tk_shop_ranking": "platform_ranking_signal",
    "platform_strategy": "platform_playbook",
    "platform_rule_playbook": "platform_playbook",
    "玩法策略": "platform_playbook",
    "product_term": "product_lexicon",
    "keyword_lexicon": "product_lexicon",
    "产品词库": "product_lexicon",
    "holiday_db": "holiday_calendar",
    "season_calendar": "holiday_calendar",
    "节日词库": "holiday_calendar",
    "restricted_word": "restricted_term",
    "risk_term": "restricted_term",
    "违禁词": "restricted_term",
    "ip_entity": "ip_entity",
    "rights_entity": "ip_entity",
    "侵权实体": "ip_entity",
    "creative_asset": "creative_asset",
    "creative_decomp": "creative_decomposition",
    "素材拆解": "creative_decomposition",
    "lead_intent": "lead_signal",
    "customer_intent": "lead_signal",
    "线索信号": "lead_signal",
    "creative_pattern_weight": "creative_pattern_weight",
    "agent_permission": "agent_permission",
    "permission_guardrail": "agent_permission",
    "signal_baseline": "signal_baseline",
    "experiment_rule": "experiment_rule",
    "store": "store_profile",
    "shop": "store_profile",
    "shop_profile": "store_profile",
    "store_account": "store_profile",
    "store_registry": "store_profile",
    "product_selection_sop": "selection_playbook",
    "selection_sop": "selection_playbook",
    "tk_selection": "selection_playbook",
    "tk_product_selection": "selection_playbook",
    "store_health": "store_health_event",
    "shop_health": "store_health_event",
    "account_health": "store_health_event",
    "store_operation": "store_operation_event",
    "listing_operation": "store_operation_event",
    "promotion_operation": "store_operation_event",
    "backend_path": "store_operation_event",
    "viral_video": "viral_content_signal",
    "viral_content": "viral_content_signal",
    "viral_signal": "viral_content_signal",
    "content_signal": "viral_content_signal",
    "creator_spike": "creator_spike_event",
    "creator_alert": "creator_spike_event",
    "video_analysis": "video_breakdown",
    "video_deconstruction": "video_breakdown",
    "content_breakdown": "video_breakdown",
    "script": "video_script",
    "video_script": "video_script",
    "store_video_script": "video_script",
    "owned_video_script": "video_script",
    "influencer_video_script": "video_script",
    "creator_script": "video_script",
    "influencer_brief": "video_script",
    "social_account": "social_account_profile",
    "video_account": "social_account_profile",
    "tk_video_account": "social_account_profile",
    "tiktok_account": "social_account_profile",
    "channel_account": "social_account_profile",
    "video_publish": "video_publish_plan",
    "publish_plan": "video_publish_plan",
    "tk_publish_plan": "video_publish_plan",
    "aip_publish_plan": "video_publish_plan",
    "video_post_plan": "video_publish_plan",
    "creative_inspiration": "creative_inspiration",
    "material_inspiration": "creative_inspiration",
    "creative_asset_idea": "creative_inspiration",
    "original_material": "creative_inspiration",
    "素材灵感": "creative_inspiration",
    "industry_research": "industry_research_asset",
    "research_asset": "industry_research_asset",
    "brand_library": "industry_research_asset",
    "product_library": "industry_research_asset",
    "pain_point_library": "industry_research_asset",
    "keyword_library": "industry_research_asset",
    "content_account_library": "industry_research_asset",
    "competitor_site_library": "industry_research_asset",
    "knowledge_map": "industry_research_asset",
    "opportunity_list": "industry_research_asset",
    "forbidden_word": "compliance_term",
    "prohibited_word": "compliance_term",
    "restricted_word": "compliance_term",
    "trademark_risk": "compliance_term",
    "ip_risk": "compliance_term",
    "compliance": "compliance_term",
    "image_ip_risk": "ip_image_risk",
    "ip_image_risk": "ip_image_risk",
    "image_infringement": "ip_image_risk",
    "tro_risk": "ip_image_risk",
    "tro_image": "ip_image_risk",
    "copyright_image": "ip_image_risk",
    "pod_ip_risk": "ip_image_risk",
    "review": "review_insight",
    "bad_review": "review_insight",
    "complaint": "review_insight",
    "negative_review": "review_insight",
    "product_pain_point": "review_insight",
    "feedback": "feedback_ticket",
    "feedback_ticket": "feedback_ticket",
    "complaint_suggestion": "feedback_ticket",
    "bug_report": "feedback_ticket",
    "user_complaint": "feedback_ticket",
    "feature_request": "feedback_ticket",
    "用户反馈": "feedback_ticket",
    "投诉建议": "feedback_ticket",
    "collection_job": "collection_job",
    "data_collection_job": "collection_job",
    "platform_collection": "collection_job",
    "autonomous_collection": "collection_job",
    "pod_admin": "pod_admin_snapshot",
    "pod_admin_snapshot": "pod_admin_snapshot",
    "pod_platform": "pod_admin_snapshot",
    "store_metric": "store_metric_snapshot",
    "store_metrics": "store_metric_snapshot",
    "sales_dashboard": "store_metric_snapshot",
    "sales_snapshot": "store_metric_snapshot",
    "sales_metric": "store_metric_snapshot",
    "shop_sales": "store_metric_snapshot",
    "return_snapshot": "store_metric_snapshot",
    "execution_result": "execution_result",
    "action_result": "execution_result",
    "approval_result": "execution_result",
    "closed_loop_result": "execution_result",
    "strategy_memory": "strategy_memory",
    "playbook_memory": "strategy_memory",
    "operation_memory": "strategy_memory",
    "web_ai_meeting": "web_ai_meeting",
    "ai_meeting": "web_ai_meeting",
    "external_ai_review": "web_ai_meeting",
    "电商智能复盘": "web_ai_meeting",
    "conversation_import": "conversation_import",
    "chat_import": "conversation_import",
    "聊天导入": "conversation_import",
    "knowledge_item": "knowledge_item",
    "knowledge": "knowledge_item",
    "knowledge_base": "knowledge_item",
    "知识库": "knowledge_item",
    "knowledge_edge": "knowledge_edge",
    "knowledge_graph": "knowledge_edge",
    "知识图谱": "knowledge_edge",
    "knowledge_concept_weight": "knowledge_concept_weight",
    "concept_weight": "knowledge_concept_weight",
    "learning_weight": "knowledge_concept_weight",
    "概念权重": "knowledge_concept_weight",
    "source_document": "source_document",
    "source": "source_document",
    "provenance": "source_document",
    "来源文档": "source_document",
    "来源溯源": "source_document",
    "raw_asset": "raw_asset",
    "rawasset": "raw_asset",
    "原始资产": "raw_asset",
    "import_batch": "import_batch",
    "importbatch": "import_batch",
    "导入批次": "import_batch",
    "attachment_asset": "attachment_asset",
    "asset": "attachment_asset",
    "附件": "attachment_asset",
    "knowledge_edge_record": "knowledge_edge_record",
    "commerce_knowledge_edge": "knowledge_edge_record",
    "知识边": "knowledge_edge_record",
    "order_item": "order_item",
    "order_line": "order_item",
    "订单行": "order_item",
    "platform_rule_snapshot": "platform_rule_snapshot",
    "rule_snapshot": "platform_rule_snapshot",
    "平台规则快照": "platform_rule_snapshot",
    "finance_transaction": "finance_transaction",
    "finance_ledger": "finance_transaction",
    "财务流水": "finance_transaction",
    "inventory_ledger": "inventory_ledger",
    "inventory_movement": "inventory_ledger",
    "库存流水": "inventory_ledger",
    "entity_tag_map": "entity_tag_map",
    "tag_map": "entity_tag_map",
    "标签映射": "entity_tag_map",
    "experiment_run": "experiment_run",
    "experiment": "experiment_run",
    "实验记录": "experiment_run",
    "action_outcome": "action_outcome",
    "outcome": "action_outcome",
    "结果反馈": "action_outcome",
    "approval_request": "approval_request",
    "approval": "approval_request",
    "审批请求": "approval_request",
    "audit_log": "audit_log",
    "audit": "audit_log",
    "审计日志": "audit_log",
    "taxonomy_dictionary": "taxonomy_dictionary",
    "taxonomy": "taxonomy_dictionary",
    "标签字典": "taxonomy_dictionary",
    "pii_vault": "pii_vault",
    "pii": "pii_vault",
    "敏感信息": "pii_vault",
    "learning_event": "learning_event",
    "学习事件": "learning_event",
    "knowledge_node": "knowledge_node",
    "知识节点": "knowledge_node",
    "agent_registry": "agent_registry",
    "agent": "agent_registry",
    "agent注册表": "agent_registry",
    "enterprise_account": "enterprise_account",
    "企业客户": "enterprise_account",
    "quote": "quote",
    "quotation": "quote",
    "报价": "quote",
    "contract_record": "contract_record",
    "contract": "contract_record",
    "合同": "contract_record",
    "inquiry": "inquiry",
    "询盘": "inquiry",
    "agent_evaluation": "agent_evaluation",
    "agent_scorecard": "agent_evaluation",
    "agent评价": "agent_evaluation",
    "source_chunk": "source_chunk",
    "sourcechunk": "source_chunk",
    "source_span": "source_chunk",
    "来源片段": "source_chunk",
    "ingestion_run": "ingestion_run",
    "ingestion": "ingestion_run",
    "crawler_run": "ingestion_run",
    "采集运行": "ingestion_run",
    "lineage_event": "lineage_event",
    "lineage": "lineage_event",
    "数据血缘": "lineage_event",
    "evidence_claim": "evidence_claim",
    "claim": "evidence_claim",
    "证据声明": "evidence_claim",
    "policy_document": "policy_document",
    "policy_doc": "policy_document",
    "platform_policy_doc": "policy_document",
    "政策文档": "policy_document",
    "policy_rule": "policy_rule",
    "platform_rule": "policy_rule",
    "政策规则": "policy_rule",
    "policy_diff": "policy_diff",
    "rule_diff": "policy_diff",
    "政策变更": "policy_diff",
    "entity_alias": "entity_alias",
    "alias": "entity_alias",
    "实体别名": "entity_alias",
    "knowledge_revision": "knowledge_revision",
    "knowledge_version": "knowledge_revision",
    "知识版本": "knowledge_revision",
    "eval_case": "eval_case",
    "evaluation_case": "eval_case",
    "评测用例": "eval_case",
    "eval_run": "eval_run",
    "evaluation_run": "eval_run",
    "评测运行": "eval_run",
    "judge_result": "judge_result",
    "eval_result": "judge_result",
    "评测结果": "judge_result",
    "error_slice": "error_slice",
    "error_cluster": "error_slice",
    "错误切片": "error_slice",
    "rollback_gate": "rollback_gate",
    "rollback": "rollback_gate",
    "回滚门": "rollback_gate",
    "model_registry": "model_registry",
    "model_version": "model_registry",
    "模型注册": "model_registry",
    "prompt_version": "prompt_version",
    "prompt_registry": "prompt_version",
    "提示词版本": "prompt_version",
    "event_inbox": "event_inbox",
    "event": "event_inbox",
    "事件收件箱": "event_inbox",
    "event_dedup": "event_dedup",
    "idempotency": "event_dedup",
    "事件去重": "event_dedup",
    "task_queue": "task_queue",
    "queue_task": "task_queue",
    "任务队列": "task_queue",
    "dead_letter": "dead_letter",
    "dead_letter_queue": "dead_letter",
    "失败队列": "dead_letter",
    "agent_action_log": "agent_action_log",
    "agent_action": "agent_action_log",
    "agent动作日志": "agent_action_log",
    "data_subject_request": "data_subject_request",
    "dsr": "data_subject_request",
    "隐私请求": "data_subject_request",
    "retention_policy": "retention_policy",
    "数据保留策略": "retention_policy",
    "delete_workflow": "delete_workflow",
    "deletion_workflow": "delete_workflow",
    "删除流程": "delete_workflow",
    "consent_record": "consent_record",
    "consent": "consent_record",
    "授权同意": "consent_record",
    "sensitive_data_flag": "sensitive_data_flag",
    "sensitive_flag": "sensitive_data_flag",
    "敏感数据标记": "sensitive_data_flag",
    "company": "company",
    "enterprise_company": "company",
    "公司主体": "company",
    "company_user": "company_user",
    "enterprise_user": "company_user",
    "企业用户": "company_user",
    "shared_catalog": "shared_catalog",
    "catalog": "shared_catalog",
    "共享目录": "shared_catalog",
    "quote_line": "quote_line",
    "quotation_line": "quote_line",
    "报价行": "quote_line",
    "price_list": "price_list",
    "pricelist": "price_list",
    "价格表": "price_list",
    "settlement": "settlement",
    "结算": "settlement",
    "payout": "payout",
    "打款": "payout",
    "invoice": "invoice",
    "发票": "invoice",
    "return_rma": "return_rma",
    "rma": "return_rma",
    "退货RMA": "return_rma",
    "refund_record": "refund_record",
    "refund": "refund_record",
    "退款记录": "refund_record",
    "performance_alert": "performance_alert",
    "performance_signal": "performance_alert",
    "经营预警": "performance_alert",
    "account_health": "account_health",
    "account_health_snapshot": "account_health",
    "账号健康": "account_health",
    "raw_extraction_run": "raw_extraction_run",
    "extraction_run": "raw_extraction_run",
    "ocr_run": "raw_extraction_run",
    "asr_run": "raw_extraction_run",
    "原始提取运行": "raw_extraction_run",
    "policy_snapshot": "policy_snapshot",
    "规则快照": "policy_snapshot",
    "banned_term": "banned_term",
    "banned_word": "banned_term",
    "forbidden_term": "banned_term",
    "禁词": "banned_term",
    "违禁词": "banned_term",
    "keyword_intelligence": "keyword_intelligence",
    "keyword_bank": "keyword_intelligence",
    "关键词库": "keyword_intelligence",
    "长尾词": "keyword_intelligence",
    "蓝海词": "keyword_intelligence",
    "热点词": "keyword_intelligence",
    "agent_workspace_snapshot": "agent_workspace_snapshot",
    "ai_employee_workspace": "agent_workspace_snapshot",
    "员工工作台": "agent_workspace_snapshot",
    "agent_distillation_pack": "agent_distillation_pack",
    "distillation_pack": "agent_distillation_pack",
    "蒸馏包": "agent_distillation_pack",
    "ip_registry": "ip_registry",
    "ip_database": "ip_registry",
    "ip_right": "ip_registry",
    "侵权库": "ip_registry",
    "知识产权库": "ip_registry",
    "competitor_snapshot": "competitor_snapshot",
    "competitor_history": "competitor_snapshot",
    "竞品快照": "competitor_snapshot",
    "listing_snapshot": "listing_snapshot",
    "listing_history": "listing_snapshot",
    "listing快照": "listing_snapshot",
    "price_history": "price_history",
    "price_snapshot": "price_history",
    "价格历史": "price_history",
    "video_scene": "video_scene",
    "scene": "video_scene",
    "视频场景": "video_scene",
    "video_highlight_frame": "video_highlight_frame",
    "highlight_frame": "video_highlight_frame",
    "高光帧": "video_highlight_frame",
    "video_comment": "video_comment",
    "视频评论": "video_comment",
    "video_comment_intelligence": "video_comment_intelligence",
    "comment_intelligence": "video_comment_intelligence",
    "评论智能": "video_comment_intelligence",
    "knowledge_provenance": "knowledge_provenance",
    "provenance_link": "knowledge_provenance",
    "知识溯源": "knowledge_provenance",
    "knowledge_score_record": "knowledge_score_record",
    "knowledge_score_table": "knowledge_score_record",
    "知识评分": "knowledge_score_record",
    "concept_weight_history": "concept_weight_history",
    "concept_history": "concept_weight_history",
    "概念权重历史": "concept_weight_history",
    "quality_metric_snapshot": "quality_metric_snapshot",
    "quality_metric": "quality_metric_snapshot",
    "质量指标": "quality_metric_snapshot",
    "claim_requirement": "claim_requirement",
    "claim_rule": "claim_requirement",
    "claims_library": "claim_requirement",
    "声明规则": "claim_requirement",
    "宣称规则": "claim_requirement",
    "compliance_artifact": "compliance_artifact",
    "certificate": "compliance_artifact",
    "certification": "compliance_artifact",
    "license_document": "compliance_artifact",
    "证照": "compliance_artifact",
    "合规证据": "compliance_artifact",
    "content_rights_asset": "content_rights_asset",
    "music_rights": "content_rights_asset",
    "audio_rights": "content_rights_asset",
    "creator_rights": "content_rights_asset",
    "音乐授权": "content_rights_asset",
    "内容权利": "content_rights_asset",
    "commercial_disclosure": "commercial_disclosure",
    "creator_disclosure": "commercial_disclosure",
    "affiliate_disclosure": "commercial_disclosure",
    "商业披露": "commercial_disclosure",
    "达人披露": "commercial_disclosure",
    "enforcement_event": "enforcement_event",
    "violation_event": "enforcement_event",
    "account_penalty": "enforcement_event",
    "处罚事件": "enforcement_event",
    "账号处罚": "enforcement_event",
    "appeal_case": "appeal_case",
    "appeal_precedent": "appeal_case",
    "appeal_record": "appeal_case",
    "申诉案例": "appeal_case",
    "申诉先例": "appeal_case",
    "query_snapshot": "query_snapshot",
    "search_query_snapshot": "query_snapshot",
    "keyword_snapshot": "query_snapshot",
    "搜索快照": "query_snapshot",
    "关键词快照": "query_snapshot",
    "creative_snapshot": "creative_snapshot",
    "creative_history": "creative_snapshot",
    "top_ads_snapshot": "creative_snapshot",
    "创意快照": "creative_snapshot",
    "素材快照": "creative_snapshot",
    "seasonal_event": "seasonal_event",
    "holiday_event": "seasonal_event",
    "retail_event": "seasonal_event",
    "节日事件": "seasonal_event",
    "营销节点": "seasonal_event",
    "creative_pattern": "creative_pattern",
    "script_pattern": "creative_pattern",
    "hook_pattern": "creative_pattern",
    "素材模式": "creative_pattern",
    "脚本模式": "creative_pattern",
    "signal_event": "signal_event",
    "commerce_signal": "signal_event",
    "趋势信号": "signal_event",
    "机会信号": "signal_event",
    "signal_snapshot": "signal_snapshot",
    "signal_history": "signal_snapshot",
    "信号快照": "signal_snapshot",
    "signal_threshold": "signal_threshold",
    "signal_rule": "signal_threshold",
    "信号阈值": "signal_threshold",
    "signal_alert": "signal_alert",
    "signal_warning": "signal_alert",
    "信号预警": "signal_alert",
    "signal_weight": "signal_weight",
    "signal_score_weight": "signal_weight",
    "信号权重": "signal_weight",
    "hypothesis": "hypothesis",
    "opportunity_hypothesis": "hypothesis",
    "商业假设": "hypothesis",
    "机会假设": "hypothesis",
    "hypothesis_evidence": "hypothesis_evidence",
    "假设证据": "hypothesis_evidence",
    "hypothesis_score": "hypothesis_score",
    "假设评分": "hypothesis_score",
    "v2_experiment": "experiment",
    "experiment_plan": "experiment",
    "实验计划": "experiment",
    "experiment_variant": "experiment_variant",
    "实验变量": "experiment_variant",
    "experiment_metric": "experiment_metric",
    "实验指标": "experiment_metric",
    "experiment_stop_rule": "experiment_stop_rule",
    "stop_rule": "experiment_stop_rule",
    "止损规则": "experiment_stop_rule",
    "experiment_scale_rule": "experiment_scale_rule",
    "scale_rule": "experiment_scale_rule",
    "扩量规则": "experiment_scale_rule",
    "experiment_outcome": "experiment_outcome",
    "实验结果": "experiment_outcome",
    "pattern_weight": "pattern_weight",
    "模式权重": "pattern_weight",
    "pattern_history": "pattern_history",
    "模式历史": "pattern_history",
    "strategy_adjustment": "strategy_adjustment",
    "策略调整": "strategy_adjustment",
    "priority_rebalance_log": "priority_rebalance_log",
    "优先级重排": "priority_rebalance_log",
    "task_priority": "task_priority",
    "任务优先级": "task_priority",
    "backlog": "backlog",
    "机会池": "backlog",
    "priority_score": "priority_score",
    "priority_score_log": "priority_score",
    "优先级分数": "priority_score",
}


def canonical_record_type(record_type: str) -> str:
    return RECORD_TYPE_ALIASES.get(record_type, record_type)


FIELD_ALIASES: dict[str, list[str]] = {
    "product_name": ["产品", "品名", "product", "product_name"],
    "category": ["类目", "category"],
    "platform": ["平台", "platform"],
    "url": ["链接", "url", "link", "source_url"],
    "screenshot_path": ["截图", "截图路径", "screenshot"],
    "selling_price": ["售价", "卖价", "selling_price", "price"],
    "landed_cost": ["成本", "落地成本", "landed_cost", "cost"],
    "sample_cost": ["寄样成本", "sample_cost"],
    "influencer_cost": ["达人成本", "达人费用", "influencer_cost"],
    "ad_spend": ["广告花费", "投流花费", "ad_spend"],
    "total_revenue": ["销售额", "revenue", "gmv"],
    "net_revenue": ["净销售额", "net_revenue", "net_sales"],
    "refund_amount": ["退款金额", "refund_amount", "refunds_amount"],
    "settlement_amount": ["结算金额", "回款金额", "打款金额", "settlement_amount", "payout_amount", "net_payout"],
    "platform_fee": ["平台费", "platform_fee", "marketplace_fee"],
    "commission_fee": ["佣金", "commission", "commission_fee", "referral_fee"],
    "transaction_fee": ["交易费", "transaction_fee", "payment_fee"],
    "shipping_fee": ["物流费", "运费", "shipping_fee", "shipping_cost"],
    "tax_amount": ["税费", "tax", "tax_amount"],
    "adjustment_amount": ["调整金额", "adjustment", "adjustment_amount"],
    "reserve_amount": ["预留金额", "reserve_amount", "account_reserve"],
    "total_profit": ["利润", "profit"],
    "roi": ["ROI", "roi", "roas"],
    "lifecycle": ["生命周期", "life_cycle", "lifecycle"],
    "influencer_type": ["达人类型", "达人", "influencer_type"],
    "influencer_handle": ["达人昵称", "昵称", "handle", "influencer_handle"],
    "profile_url": ["达人链接", "profile_url", "profile"],
    "follower_count": ["粉丝", "粉丝数", "followers", "follower_count"],
    "avg_views": ["均播", "平均播放", "avg_views"],
    "engagement_rate": ["互动率", "engagement_rate"],
    "quote_price": ["报价", "quote", "quote_price"],
    "video_posted": ["是否发视频", "出视频", "video_posted"],
    "orders": ["出单", "订单", "orders"],
    "order_count": ["订单数", "order_count", "order_total"],
    "unit_count": ["件数", "销量件数", "units", "unit_count", "units_sold"],
    "return_count": ["退货数", "return_count", "returns"],
    "refund_count": ["退款单数", "refund_count", "refund_orders"],
    "content_angle": ["素材", "素材方向", "content_angle"],
    "hook": ["Hook", "hook", "钩子"],
    "main_visual_action": ["素材动作", "主视觉", "main_visual_action"],
    "failure_reason": ["失败原因", "亏损原因", "原因", "failure_reason"],
    "winning_reason": ["赚钱原因", "爆的原因", "winning_reason"],
    "lessons": ["复盘", "结论", "lessons"],
    "product_type": ["品类", "款式", "product_type"],
    "gender": ["性别", "gender"],
    "color": ["颜色", "color"],
    "size_range": ["尺码", "size", "size_range"],
    "weight_gsm": ["克重", "weight", "gsm", "weight_gsm"],
    "inventory_qty": ["库存", "inventory", "inventory_qty"],
    "unit_cost": ["单件成本", "unit_cost"],
    "production_days": ["生产周期", "production_days"],
    "shipping_days": ["发货周期", "shipping_days"],
    "playbook_name": ["SOP名称", "方法论", "playbook_name"],
    "selection_stage": ["选品阶段", "selection_stage"],
    "selection_process": ["选品流程", "selection_process"],
    "selection_tools": ["选品工具", "选品平台", "selection_tools"],
    "selection_direction": ["选品方向", "selection_direction"],
    "selection_metrics": ["选品指标", "selection_metrics"],
    "amazon_validation_rules": ["亚马逊验证", "亚马逊反推", "amazon_validation_rules"],
    "scoring_framework": ["评分框架", "整体框架", "scoring_framework"],
    "avoid_rules": ["避坑规则", "avoid_rules"],
    "detail_checklist": ["细节事项", "detail_checklist"],
    "source_image_path": ["来源图片", "source_image_path"],
    "english_label": ["英文标签", "标签", "english_label"],
    "chinese_meaning": ["中文理解", "中文", "chinese_meaning"],
    "audience_identity": ["对应人群", "人群", "audience_identity"],
    "buying_motivation": ["购买动机", "buying_motivation"],
    "holiday_name": ["节日", "holiday", "holiday_name"],
    "date_or_period": ["日期", "周期", "date_or_period"],
    "metric_date": ["指标日期", "metric_date", "sales_date"],
    "snapshot_start": ["开始时间", "start_date", "snapshot_start", "period_start"],
    "snapshot_end": ["结束时间", "end_date", "snapshot_end", "period_end"],
    "settlement_id": ["结算单号", "settlement_id", "payout_id", "statement_id"],
    "report_type": ["报表类型", "report_type", "statement_type"],
    "currency": ["币种", "currency"],
    "source_platform": ["来源", "source", "source_platform"],
    "marketplace": ["marketplace", "platform_marketplace", "平台市场", "平台"],
    "ranking_type": ["ranking_type", "rank_type", "榜单类型", "榜单"],
    "rank_position": ["rank_position", "rank", "排名"],
    "rank_delta": ["rank_delta", "rank_change", "排名变化"],
    "ranking_page": ["ranking_page", "榜单页面", "页面"],
    "category_path": ["category_path", "category_tree", "类目路径"],
    "product_id": ["product_id", "asin", "sku", "item_id"],
    "seller_name": ["seller_name", "shop_name", "store_name", "店铺名", "卖家名"],
    "sales_count": ["sales_count", "sales", "销量"],
    "gmv": ["gmv", "ranking_revenue"],
    "price": ["platform_price", "ranking_price", "榜单价格"],
    "review_count": ["review_count", "reviews", "评论数"],
    "rating": ["rating", "评分"],
    "snapshot_window": ["snapshot_window", "time_window", "统计周期"],
    "visible_growth_signal": ["增长信号", "信号", "visible_growth_signal"],
    "rule_type": ["规则类型", "rule_type"],
    "summary": ["规则摘要", "摘要", "summary"],
    "risk_level": ["风险等级", "risk_level"],
    "immediate_action": ["立即动作", "immediate_action"],
    "store_id": ["店铺", "店铺ID", "店铺编号", "store_id"],
    "store_name": ["店铺名称", "store_name"],
    "store_group": ["店铺分组", "store_group"],
    "browser_profile": ["浏览器环境", "比特环境", "browser_profile"],
    "bit_profile_id": ["比特窗口", "比特窗口ID", "bit_profile_id"],
    "shop_region": ["店铺地区", "国家", "区域", "shop_region"],
    "country_code": ["国家代码", "country_code", "country"],
    "currency": ["币种", "currency"],
    "timezone": ["时区", "timezone"],
    "language": ["语言", "language"],
    "fulfillment_model": ["履约模式", "发货模式", "fulfillment_model"],
    "warehouse_region": ["仓库区域", "warehouse_region"],
    "ip_region": ["IP区域", "ip_region"],
    "proxy_profile_ref": ["IP节点引用", "代理引用", "proxy_profile_ref"],
    "legal_entity_ref": ["法人引用", "主体引用", "legal_entity_ref"],
    "contact_email_ref": ["邮箱引用", "contact_email_ref"],
    "phone_ref": ["电话引用", "phone_ref"],
    "credential_ref": ["密码引用", "账号密码引用", "credential_ref"],
    "seller_center_url": ["卖家后台", "后台链接", "seller_center_url"],
    "operating_status": ["运营状态", "operating_status"],
    "adaptation_notes": ["适配备注", "adaptation_notes"],
    "account_status": ["账号状态", "account_status"],
    "health_status": ["店铺状态", "健康状态", "health_status"],
    "health_score": ["店铺健康评分", "健康分", "health_score"],
    "probation_status": ["店铺考察期", "考察期", "probation_status"],
    "pending_rectification_count": ["待整改违规", "pending_rectification_count"],
    "appealable_violation_count": ["可申诉违规", "appealable_violation_count"],
    "rejected_product_count": ["被拒商品", "rejected_product_count"],
    "low_inventory_count": ["商品低库存", "low_inventory_count"],
    "pending_shipment_count": ["订单待发货", "pending_shipment_count"],
    "pending_after_sales_count": ["售后待处理", "pending_after_sales_count"],
    "daily_order_limit": ["每日订单上限", "daily_order_limit"],
    "max_product_limit": ["最大商品数量", "max_product_limit"],
    "observed_path": ["页面路径", "后台路径", "observed_path"],
    "operation_type": ["操作类型", "operation_type"],
    "operation_path": ["操作路径", "operation_path"],
    "required_inputs": ["所需输入", "required_inputs"],
    "guardrails": ["风控要求", "注意事项", "guardrails"],
    "blocked_by": ["阻塞原因", "blocked_by"],
    "operation_status": ["操作状态", "operation_status"],
    "video_url": ["视频链接", "短视频链接", "video_url", "video link", "video"],
    "creator_handle": ["达人昵称", "作者", "博主", "creator_handle", "creator", "author"],
    "contact_email": ["达人邮箱", "商务邮箱", "联系邮箱", "邮箱", "contact_email", "creator_email", "business_email", "email"],
    "contact_phone": ["达人电话", "商务电话", "联系电话", "电话", "contact_phone", "creator_phone", "business_phone", "phone", "phone_number"],
    "whatsapp": ["WhatsApp", "whatsapp", "whatsapp_number", "whatsapp_url"],
    "dm_url": ["私信入口", "私信链接", "DM", "dm_url", "contact_url", "tiktok_dm_url", "instagram_dm_url"],
    "business_contact": ["商务联系人", "经纪人", "机构", "business_contact", "agent_contact", "contact_person", "agency"],
    "contact_method": ["首选联系", "联系方式", "联系渠道", "contact_method", "preferred_contact_method", "contact_channel"],
    "product_theme": ["产品主题", "商品主题", "人群主题", "product_theme", "product theme"],
    "content_theme": ["素材主题", "内容主题", "content_theme", "content theme"],
    "growth_window": ["增长窗口", "周期", "growth_window", "growth window"],
    "previous_views": ["昨日播放", "原播放", "之前播放", "previous_views", "before_views"],
    "current_views": ["今日播放", "当前播放", "现在播放", "current_views", "views"],
    "view_growth_rate": ["播放增长率", "view_growth_rate", "growth_rate"],
    "growth_multiplier": ["增长倍数", "growth_multiplier", "growth multiple"],
    "baseline_avg_views": ["历史均播", "近30天均播", "baseline_avg_views", "baseline views"],
    "latest_video_views": ["最新视频播放", "爆款视频播放", "latest_video_views"],
    "spike_multiplier": ["异动倍数", "爆发倍数", "spike_multiplier"],
    "timeline_structure": ["视频结构", "分镜结构", "timeline_structure", "structure"],
    "hook_text": ["钩子", "开头话术", "hook_text", "hook"],
    "hook_type": ["钩子类型", "hook_type"],
    "audience_profile": ["人群画像", "audience_profile", "audience"],
    "scene": ["场景", "scene"],
    "emotion": ["情绪", "emotion"],
    "caption_text": ["标题字幕", "字幕", "caption_text", "caption"],
    "spoken_text": ["口播", "spoken_text", "voiceover"],
    "script_lines": ["话术", "脚本", "script_lines", "script"],
    "script_type": ["脚本类型", "用途", "script_type", "script use"],
    "target_store_id": ["目标店铺", "target_store_id"],
    "target_creator_type": ["达人类型", "target_creator_type", "creator type"],
    "shooting_owner": ["拍摄方", "执行方", "shooting_owner"],
    "shot_list": ["镜头清单", "拍摄清单", "shot_list", "shots"],
    "on_screen_text": ["屏幕字幕", "on_screen_text", "screen text"],
    "voiceover": ["口播文案", "voiceover", "voice over"],
    "cta": ["转化动作", "CTA", "cta", "call_to_action"],
    "product_showcase_points": ["产品展示点", "product_showcase_points"],
    "creator_brief": ["达人brief", "达人要求", "creator_brief"],
    "store_script": ["店铺自播脚本", "店铺脚本", "store_script"],
    "influencer_script": ["达人脚本", "influencer_script"],
    "usage_guardrails": ["禁区", "注意事项", "usage_guardrails"],
    "source_breakdown_id": ["来源拆解", "source_breakdown_id"],
    "account_role": ["账号角色", "account_role", "role"],
    "account_handle": ["账号昵称", "账号handle", "account_handle", "handle"],
    "official_account_handle": ["官方号", "official_account_handle"],
    "channel_account_handles": ["渠道号", "渠道账号", "channel_accounts", "channel_account_handles"],
    "target_account_handle": ["目标发布账号", "target_account_handle"],
    "aip_provider": ["AIP软件", "AIP", "aip_provider", "publisher_app"],
    "aip_login_url": ["AIP登录", "aip_login_url"],
    "aip_bind_status": ["AIP绑定状态", "aip_bind_status"],
    "can_publish_video": ["可发视频", "can_publish_video"],
    "video_file_ref": ["视频文件", "video_file_ref", "asset_ref"],
    "publish_title": ["发布标题", "publish_title", "post_title"],
    "publish_tags": ["发布标签", "标签", "publish_tags", "hashtags"],
    "music_name": ["音乐", "音乐名", "music_name"],
    "music_source": ["音乐来源", "music_source"],
    "music_license_status": ["音乐版权状态", "music_license_status"],
    "music_volume": ["音乐音量", "music_volume"],
    "original_audio_volume": ["原声音量", "original_audio_volume"],
    "voiceover_volume": ["口播音量", "voiceover_volume"],
    "music_guardrails": ["音乐注意事项", "music_guardrails"],
    "publish_window": ["发布时间", "publish_window"],
    "publish_status": ["发布状态", "publish_status"],
    "creative_angle": ["素材角度", "创意角度", "creative_angle"],
    "material_type": ["素材类型", "material_type"],
    "originality_type": ["原创类型", "originality_type"],
    "source_hooks": ["来源Hook", "source_hooks"],
    "source_titles": ["来源标题", "source_titles"],
    "source_tags": ["来源标签", "source_tags"],
    "source_scripts": ["来源脚本", "source_scripts"],
    "derived_from_memory": ["参考记忆", "derived_from_memory"],
    "creative_prompt": ["素材提示词", "creative_prompt"],
    "reuse_boundaries": ["复用边界", "reuse_boundaries"],
    "original_shot_plan": ["原创镜头计划", "original_shot_plan"],
    "research_asset_type": [
        "research_asset_type",
        "asset_type",
        "library_type",
        "研究资产类型",
        "资料库类型",
        "模块",
    ],
    "industry_scope": ["industry_scope", "industry", "行业范围", "行业"],
    "brand_name": ["brand_name", "brand", "品牌", "品牌名"],
    "target_market": ["target_market", "market", "目标市场", "热销地区"],
    "positioning": ["positioning", "brand_positioning", "品牌定位", "定位"],
    "price_range": ["price_range", "价格区间"],
    "selling_points": ["selling_points", "卖点", "核心卖点"],
    "user_pain_point": ["user_pain_point", "pain_point", "用户痛点", "痛点"],
    "keyword_cluster": ["keyword_cluster", "keywords", "关键词库", "关键词", "长尾词"],
    "content_account": ["content_account", "账号", "内容账号", "内容账号库"],
    "account_type": ["account_type", "账号类型", "内容类型"],
    "competitor_site_url": ["competitor_site_url", "竞品网站", "同行网站", "竞品网站库"],
    "navigation_pattern": ["navigation_pattern", "导航结构", "导航与分类"],
    "collection_logic": ["collection_logic", "collection", "产品集合", "collection逻辑"],
    "seo_tags": ["seo_tags", "seo", "产品标签", "seo标签"],
    "blog_topic": ["blog_topic", "blog选题", "blog内容"],
    "knowledge_node": ["knowledge_node", "知识节点", "知识地图"],
    "process_stage": ["process_stage", "流程阶段", "业务流程"],
    "opportunity": ["opportunity", "机会点", "机会清单"],
    "validation_task": ["validation_task", "验证任务", "下一步验证任务"],
    "update_frequency": ["update_frequency", "更新频率"],
    "next_action": ["next_action", "下一步", "下一步动作"],
    "term": ["term", "word", "keyword", "违禁词", "禁用词", "敏感词", "风险词", "品牌词"],
    "term_type": ["term_type", "词类型", "风险词类型"],
    "risk_category": ["risk_category", "风险分类", "侵权类型", "合规分类"],
    "trademark_owner": ["trademark_owner", "权利人", "商标权利人", "品牌方"],
    "prohibited_reason": ["prohibited_reason", "禁用原因", "风险原因", "侵权原因"],
    "applies_to_platform": ["applies_to_platform", "适用平台", "平台适用范围"],
    "safe_replacement": ["safe_replacement", "替代表达", "安全替换词"],
    "detection_rule": ["detection_rule", "检测规则", "匹配规则"],
    "severity": ["severity", "严重程度", "风险等级"],
    "review_source": ["review_source", "评论来源", "差评来源", "投诉来源"],
    "review_type": ["review_type", "评论类型", "差评类型", "投诉类型"],
    "review_text": ["review_text", "评论内容", "差评内容"],
    "complaint_text": ["complaint_text", "投诉内容", "客诉内容"],
    "sentiment": ["sentiment", "情绪", "评论情绪"],
    "pain_point": ["pain_point", "产品痛点", "差评痛点"],
    "defect_area": ["defect_area", "问题部位", "问题环节"],
    "refund_reason": ["refund_reason", "退款原因", "退货原因"],
    "frequency_signal": ["frequency_signal", "出现频率", "高频信号"],
    "suggested_fix": ["suggested_fix", "改进建议", "修复建议"],
    "listing_implication": ["listing_implication", "listing影响", "详情页影响"],
    "content_implication": ["content_implication", "素材影响", "脚本影响"],
    "product_implication": ["product_implication", "产品影响", "供应链影响"],
    "evidence_count": ["evidence_count", "证据数量", "评论数量", "投诉数量"],
    "feedback_type": ["feedback_type", "反馈类型", "问题类型"],
    "feedback_source": ["feedback_source", "反馈来源", "提交人"],
    "module_area": ["module_area", "模块", "页面模块", "功能模块"],
    "page_url": ["page_url", "页面链接", "问题页面"],
    "feedback_text": ["feedback_text", "反馈内容", "问题描述", "投诉内容"],
    "actual_behavior": ["actual_behavior", "实际情况", "现在是什么样"],
    "expected_behavior": ["expected_behavior", "期望结果", "希望是什么样"],
    "suggestion": ["suggestion", "建议", "修改建议"],
    "annotation_notes": ["annotation_notes", "标注说明", "画圈说明"],
    "annotated_image_path": ["annotated_image_path", "标注图"],
    "feedback_status": ["feedback_status", "反馈状态", "处理状态"],
    "assignee": ["assignee", "负责人"],
    "collection_scope": ["collection_scope", "采集范围", "收集范围"],
    "platform_list": ["platform_list", "平台列表", "目标平台"],
    "data_window": ["data_window", "数据窗口", "历史窗口", "时间范围"],
    "collection_target": ["collection_target", "采集目标", "收集目标"],
    "source_type": ["source_type", "数据源类型", "来源类型"],
    "analysis_task": ["analysis_task", "分析任务", "AI分析任务"],
    "comment_insights": ["评论洞察", "评论区情报", "comment_insights"],
    "purchase_intent_comments": ["购买意向评论", "purchase_intent_comments"],
    "high_frequency_words": ["高频词", "high_frequency_words"],
    "conversion_words": ["转化词", "conversion_words"],
    "viral_reason": ["爆款原因", "为什么爆", "viral_reason"],
    "key_frame": ["爆点镜头", "关键镜头", "key_frame"],
    "replicate_plan": ["复刻方案", "如何复制", "replicate_plan"],
    "recommended_variations": ["复刻变体", "recommended_variations"],
    "recommended_creator_type": ["推荐达人类型", "recommended_creator_type"],
    "content_score": ["素材分", "content_score"],
}
FIELD_ALIASES.update({
    "risk_element": ["risk_element", "image_element", "侵权元素", "图片元素", "图案元素", "风险元素"],
    "element_category": ["element_category", "元素分类", "图片分类", "风险元素分类"],
    "rights_owner": ["rights_owner", "权利人", "品牌方", "版权方", "原告"],
    "plaintiff": ["plaintiff", "原告", "TRO原告"],
    "case_number": ["case_number", "case_no", "案号", "案件号"],
    "tro_status": ["tro_status", "TRO状态", "冻结状态"],
    "image_url": ["image_url", "图片链接", "侵权图片链接", "证据图片"],
    "evidence_url": ["evidence_url", "证据链接", "TRO链接", "投诉链接"],
    "infringing_listing_url": ["infringing_listing_url", "侵权链接", "风险链接", "需下架链接", "商品链接"],
    "infringing_store": ["infringing_store", "侵权店铺", "风险店铺"],
    "authorization_status": ["authorization_status", "授权状态", "许可状态", "是否授权", "是否允许上架"],
    "authorization_proof": ["authorization_proof", "授权证明", "授权文件", "许可证明", "品牌授权证明"],
    "license_agreement_url": ["license_agreement_url", "许可协议链接", "授权协议链接"],
    "platform_notice_url": ["platform_notice_url", "平台通知链接", "平台投诉链接"],
    "complaint_url": ["complaint_url", "投诉链接", "权利人投诉链接"],
    "authorization_review_priority": ["authorization_review_priority", "授权审核优先级", "审核优先级"],
    "match_keywords": ["match_keywords", "匹配词", "识别关键词", "元素关键词"],
    "visual_signature": ["visual_signature", "视觉特征", "图片特征", "图案特征"],
    "safe_design_rule": ["safe_design_rule", "安全设计规则", "规避规则"],
    "delist_reason": ["delist_reason", "下架原因", "移除原因"],
    "delist_priority": ["delist_priority", "下架优先级", "处理优先级"],
})

ALIAS_TO_FIELD = {
    alias.lower(): canonical
    for canonical, aliases in FIELD_ALIASES.items()
    for alias in aliases
}

KNOWN_LABELS = sorted(ALIAS_TO_FIELD, key=len, reverse=True)
LABEL_RE = re.compile(
    r"(?P<label>" + "|".join(re.escape(label) for label in KNOWN_LABELS) + r")\s*[:：]\s*",
    re.IGNORECASE,
)


def detect_record_type(text: str) -> str:
    normalized = text.lower()
    explicit_match = re.search(r"record_type\s*[:：]\s*([a-zA-Z0-9_.\-/]+)", text, re.IGNORECASE)
    if explicit_match:
        explicit_type = canonical_record_type(explicit_match.group(1).strip())
        if explicit_type in RECORD_TYPES:
            return explicit_type
    compliance_signals = [
        "compliance term",
        "forbidden word",
        "prohibited word",
        "restricted word",
        "trademark risk",
        "ip risk",
        "copyright risk",
        "patent risk",
        "uspto",
        "违禁词",
        "禁用词",
        "敏感词",
        "侵权词",
        "品牌词",
        "商标风险",
        "版权风险",
        "专利风险",
        "避免侵权",
    ]
    if any(word in normalized for word in compliance_signals):
        return "compliance_term"
    collection_signals = [
        "collection job",
        "data collection job",
        "platform collection",
        "autonomous collection",
        "historical data",
        "current data",
        "自动收集",
        "自动采集",
        "历史数据",
        "当前数据",
        "现在的数据",
        "各个平台的信息",
        "各各平台的信息",
        "收入进去",
    ]
    if any(word in normalized for word in collection_signals):
        return "collection_job"
    review_signals = [
        "review insight",
        "bad review",
        "negative review",
        "one star",
        "1-star",
        "complaint",
        "refund reason",
        "return reason",
        "差评",
        "一星评论",
        "负面评论",
        "产品评论",
        "客户投诉",
        "客诉",
        "退款原因",
        "退货原因",
        "产品痛点",
        "哪里不好",
    ]
    if any(word in normalized for word in review_signals):
        return "review_insight"
    industry_research_signals = [
        "industry research",
        "research asset",
        "brand library",
        "product library",
        "pain point library",
        "keyword library",
        "content account library",
        "competitor site library",
        "knowledge map",
        "opportunity list",
        "weekly intelligence",
        "cross-border ecommerce research",
        "行业研究系统",
        "行业数据库",
        "品牌库",
        "产品库",
        "用户痛点库",
        "痛点库",
        "关键词库",
        "内容账号库",
        "竞品网站库",
        "知识地图",
        "机会清单",
        "每周跨境电商情报报告",
        "跨境电商行业研究",
    ]
    if any(word in normalized for word in industry_research_signals):
        return "industry_research_asset"
    video_script_signals = [
        "video script",
        "store video script",
        "owned video script",
        "influencer script",
        "creator script",
        "creator brief",
        "influencer brief",
        "shot_list",
        "on_screen_text",
        "voiceover",
        "call_to_action",
        "店铺自播脚本",
        "店铺脚本",
        "达人脚本",
        "达人brief",
        "拍摄清单",
        "镜头清单",
    ]
    if any(word in normalized for word in video_script_signals):
        return "video_script"
    money_signals = ["roi", "roas", "profit", "selling_price", "price", "cost", "revenue"]
    if any(word in normalized for word in money_signals):
        return "money_case"
    if any(word in normalized for word in ["规则更新", "政策", "gmv max", "商品卡", "广告规则"]):
        return "tk_rule_update"
    store_health_signals = [
        "封店",
        "被封",
        "停用",
        "账号已停用",
        "店铺被封",
        "账号被封",
        "店铺健康",
        "店铺健康评分",
        "待整改违规",
        "可申诉违规",
        "被拒商品",
        "商品低库存",
        "店铺考察期",
        "每日订单上限",
        "account disabled",
        "account suspended",
        "shop health",
    ]
    if any(word in normalized for word in store_health_signals):
        return "store_health_event"
    store_profile_signals = [
        "店铺档案",
        "店铺分组",
        "国家代码",
        "币种",
        "时区",
        "语言",
        "比特窗口",
        "ip区域",
        "履约模式",
        "发货模式",
        "法人引用",
        "密码引用",
        "seller center",
        "store profile",
        "shop profile",
    ]
    if any(word in normalized for word in store_profile_signals):
        return "store_profile"
    store_operation_signals = [
        "后台路径",
        "操作路径",
        "添加商品",
        "商品管理",
        "上架商品",
        "商品图片",
        "主图",
        "详情图",
        "标题",
        "商品描述",
        "设置折扣",
        "促销活动",
        "营销活动",
        "报活动",
        "可报名活动",
        "活动管理",
        "叠加规则",
        "价格预测",
        "活动趋势",
        "达人联盟",
    ]
    if any(word in normalized for word in store_operation_signals):
        return "store_operation_event"
    selection_playbook_signals = [
        "tk选品篇",
        "选品测品流程",
        "选品平台",
        "选品方向",
        "选品维度指标",
        "打品的选品",
        "整体框架",
        "细节事项",
        "测品",
        "选品sop",
        "product selection",
        "selection playbook",
    ]
    if any(word in normalized for word in selection_playbook_signals):
        return "selection_playbook"
    video_breakdown_signals = [
        "video breakdown",
        "video deconstruction",
        "content breakdown",
        "timeline_structure",
        "hook_type",
        "replicate_plan",
        "0-2",
        "0 - 2",
        "钩子类型",
        "视频结构",
        "评论区情报",
        "复刻方案",
        "为什么爆",
        "爆点镜头",
    ]
    if any(word in normalized for word in video_breakdown_signals):
        return "video_breakdown"
    creator_spike_signals = [
        "creator spike",
        "creator alert",
        "latest_video_views",
        "baseline_avg_views",
        "spike_multiplier",
        "疑似爆款达人",
        "达人异动",
        "历史均播",
        "最新视频",
        "爆发倍数",
    ]
    if any(word in normalized for word in creator_spike_signals):
        return "creator_spike_event"
    viral_content_signals = [
        "viral content",
        "viral video",
        "shorts",
        "reels",
        "播放增长",
        "近24小时",
        "近7天",
        "近30天",
        "从500播放到",
        "增长最快视频",
        "爆款视频",
        "爆款素材",
    ]
    if any(word in normalized for word in viral_content_signals):
        return "viral_content_signal"
    if any(word in normalized for word in ["二审"]):
        return "tk_rule_update"
    platform_ranking_signals = [
        "bsr",
        "bs.new",
        "bs/new",
        "bs new",
        "best sellers",
        "new releases",
        "movers & shakers",
        "most wished for",
        "gift ideas",
        "amazon榜单",
        "amazon bsr",
        "amazon bs.new",
        "amazon bs/new",
        "亚马逊",
        "亚马逊榜单",
        "亚马逊bs",
        "亚马逊bs.new",
        "亚马逊bs/new",
        "tiktok shop榜单",
        "tk shop榜单",
        "tiktok shop ranking",
        "etsy trending",
        "walmart榜单",
        "shein榜单",
        "平台榜单",
        "榜单类型",
        "排名",
    ]
    if any(word in normalized for word in platform_ranking_signals):
        return "platform_ranking_signal"
    if any(word in normalized for word in ["fastmoss", "kalodata", "echotik", "amazon", "etsy", "tiktok", "walmart", "shein", "ebay", "shopify", "http"]):
        return "hot_link"
    if any(word in normalized for word in ["father's day", "mother's day", "christmas", "halloween", "thanksgiving", "4th of july", "节日"]):
        return "holiday_opportunity"
    if any(word in normalized for word in ["库存", "尺码", "克重", "水洗", "oversized", "男 t", "女 t"]):
        return "supply_chain"
    if any(word in normalized for word in ["粉丝", "均播", "报价", "是否发视频", "达人昵称"]):
        return "influencer_cooperation"
    if any(word in normalized for word in ["blue collar", "dog dad", "christian", "veteran", "patriot", "文化标签"]):
        return "culture_label"
    if any(word in normalized for word in ["roi", "赚钱", "亏", "利润", "售价", "生命周期"]):
        return "money_case"
    return "money_case"


def parse_key_values(text: str) -> dict[str, Any]:
    fields: dict[str, Any] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip().strip("-").strip()
        if not line:
            continue
        _parse_line(line, fields)
    if not fields:
        _parse_line(text.strip(), fields)
    return normalize_fields(fields)


def _parse_line(line: str, fields: dict[str, Any]) -> None:
    matches = list(LABEL_RE.finditer(line))
    if not matches:
        return
    for index, match in enumerate(matches):
        label = match.group("label").lower()
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(line)
        value = line[start:end].strip().strip("，,;；")
        if not value:
            continue
        canonical = ALIAS_TO_FIELD.get(label)
        if canonical:
            fields[canonical] = value


def normalize_fields(fields: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(fields)
    for key in [
        "selling_price",
        "landed_cost",
        "sample_cost",
        "influencer_cost",
        "ad_spend",
        "total_revenue",
        "net_revenue",
        "settlement_amount",
        "refund_amount",
        "platform_fee",
        "commission_fee",
        "transaction_fee",
        "shipping_fee",
        "tax_amount",
        "adjustment_amount",
        "reserve_amount",
        "total_profit",
        "roi",
        "quote_price",
        "engagement_rate",
        "inventory_qty",
        "unit_cost",
        "production_days",
        "shipping_days",
        "orders",
        "order_count",
        "unit_count",
        "refund_count",
        "return_count",
        "rank_position",
        "rank_delta",
        "sales_count",
        "gmv",
        "price",
        "review_count",
        "rating",
        "health_score",
        "pending_rectification_count",
        "appealable_violation_count",
        "rejected_product_count",
        "low_inventory_count",
        "pending_shipment_count",
        "pending_after_sales_count",
        "daily_order_limit",
        "max_product_limit",
        "previous_views",
        "current_views",
        "view_growth_rate",
        "growth_multiplier",
        "baseline_avg_views",
        "latest_video_views",
        "spike_multiplier",
        "content_score",
    ]:
        if key in normalized:
            normalized[key] = parse_number(normalized[key])
    for key in ["video_posted"]:
        if key in normalized:
            normalized[key] = parse_bool(normalized[key])
    return normalized


def parse_number(value: Any) -> float | int | Any:
    if isinstance(value, (int, float)):
        return value
    text = str(value).replace(",", "").replace("$", "").replace("美金", "").replace("美元", "")
    match = re.search(r"-?\d+(?:\.\d+)?", text)
    if not match:
        return value
    number = float(match.group(0))
    unit_text = text[match.end(): match.end() + 3].lower()
    if "万" in unit_text:
        number *= 10_000
    elif "亿" in unit_text:
        number *= 100_000_000
    elif unit_text.startswith("k"):
        number *= 1_000
    elif unit_text.startswith("m"):
        number *= 1_000_000
    return int(number) if number.is_integer() else number


def parse_bool(value: Any) -> bool | Any:
    text = str(value).strip().lower()
    if text in {"是", "yes", "y", "true", "1", "出了", "出"}:
        return True
    if text in {"否", "no", "n", "false", "0", "没出", "未出"}:
        return False
    return value

